import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    // Common
    appName: 'Mamora',
    tagline: 'AI-Powered Maternal Health Companion',
    welcome: 'Welcome',
    hello: 'Hello',
    goodbye: 'Goodbye',
    yes: 'Yes',
    no: 'No',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    
    // Auth
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    phone: 'Phone Number',
    name: 'Full Name',
    dueDate: 'Due Date',
    pregnancyWeek: 'Pregnancy Week',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    
    // Navigation
    dashboard: 'Dashboard',
    nutrition: 'Nutrition',
    reports: 'Reports',
    records: 'Records',
    emergency: 'Emergency',
    reminders: 'Reminders',
    hospitals: 'Hospitals',
    pharmacy: 'Pharmacy',
    chatbot: 'AI Assistant',
    
    // Dashboard
    pregnancyJourney: 'Pregnancy Journey',
    week: 'Week',
    trimester: 'Trimester',
    babySize: 'Baby Size',
    babyWeight: 'Baby Weight',
    dailyTip: 'Daily Tip',
    nextAppointment: 'Next Appointment',
    
    // Nutrition
    aiNutrition: 'AI Nutrition Advisor',
    enterSymptoms: 'Enter your symptoms or health condition',
    getRecommendations: 'Get Recommendations',
    recommendedFoods: 'Recommended Foods',
    avoidFoods: 'Foods to Avoid',
    dailyMealPlan: 'Daily Meal Plan',
    
    // Reports
    uploadReport: 'Upload Medical Report',
    uploadImage: 'Upload Image/PDF',
    analyzing: 'Analyzing...',
    hemoglobin: 'Hemoglobin',
    bloodPressure: 'Blood Pressure',
    bloodSugar: 'Blood Sugar',
    riskLevel: 'Risk Level',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    
    // Emergency
    emergencySOS: 'Emergency SOS',
    tapForHelp: 'Tap for Immediate Help',
    sendingAlert: 'Sending Alert...',
    alertSent: 'Alert Sent!',
    nearbyHospitals: 'Nearby Hospitals',
    
    // Reminders
    medicineReminder: 'Medicine Reminder',
    doctorVisit: 'Doctor Visit',
    addReminder: 'Add Reminder',
    time: 'Time',
    frequency: 'Frequency',
    
    // Chatbot
    // Emergency Alert Details
    smsSentTo: 'SMS sent to',
    locationShared: 'Location shared',
    emergencyServicesNotified: 'Emergency services notified',
    alertLogged: 'Alert logged at',
    protected: 'Protected',
    youAreHere: 'You are here',
    placesFound: 'places found',
    hospital: 'Hospital',
    police: 'Police',
    all: 'All',
    confirmEmergency: 'Confirm Emergency?',
    sosWarning: 'This will alert your emergency contacts and share your location.',
    confirm: 'Confirm',
    helpOnWay: 'Help is on the way',
    emergencyHub: 'EMERGENCY HUB',
    tapForEmergency: 'Tap for immediate help',
    ambulance: 'Ambulance',
    
    // Relax/Meditation
    relaxTime: 'Relax Time',
    forMothers: 'For Mothers',
    breathingExercise: 'Breathing Exercise',
    ready: 'Ready',
    start: 'Start',
    stop: 'Stop',
    inhale: 'Inhale',
    hold: 'Hold',
    exhale: 'Exhale',
    inhaleFor4: 'Inhale for 4 seconds',
    holdFor7: 'Hold for 7 seconds',
    exhaleFor8: 'Exhale for 8 seconds',
    breathingDesc: '4-7-8 breathing helps reduce anxiety and promotes better sleep during pregnancy',
    moreSounds: 'More Relaxing Sounds',
    benefitsForMothers: 'Benefits for Mothers',
    betterSleep: 'Better Sleep',
    reducedStress: 'Reduced Stress',
    calmMind: 'Calm Mind',
    babyBonding: 'Baby Bonding',
    
    // Exercises
    exerciseBook: 'Exercise Book',
    completed: 'Completed',
    dailyGoal: 'Daily Goal',
    min: 'min',
    kcal: 'kcal',
    recommendedForYou: 'Recommended for You',
    startExercise: 'Start Exercise',
    safetyTips: 'Safety Tips',
    tip1: 'Consult your doctor before starting any exercise',
    tip2: 'Stay hydrated - drink water before, during, and after',
    tip3: 'Stop immediately if you feel dizzy or uncomfortable',
    tip4: 'Avoid exercises that require lying on your back after week 16',
    previous: 'Previous',
    next: 'Next',
    finish: 'Finish',
    easy: 'Easy',
    hard: 'Hard',
    
    // Voice Assistant
    voiceAssistant: 'Voice Assistant',
    tryAsking: 'Try asking',
    
    // Navigation
    home: 'Home',
    roadmap: 'Roadmap',
    reportAnalysis: 'Report Analysis',
    map: 'Care & SOS',
    diet: 'Diet',
    exercise: 'Exercise',
    relax: 'Relax',
    sos: 'SOS',
    
    // Dashboard additional
    viewAll: 'View All',
    tapToUpload: 'Tap to upload your medical report',
    supports: 'Supports',
    bloodTests: 'Blood tests',
    ultrasound: 'Ultrasound',
    bpReadings: 'BP readings',
    healthOverview: 'Health Overview',
    dietProgress: 'Diet Progress',
    viewPlan: 'View Plan',
    quickActions: 'Quick Actions',
    
    // Login/Register additional
    fullName: 'Full Name',
    enterName: 'Enter your full name',
    age: 'Age',
    confirmPassword: 'Confirm Password',
    createAccount: 'Create Account',
  
    navVoiceAssistant: '🎙️ Voice Assistant',
    
    // Custom Additions for Mamora Overhaul
    profile: 'Profile',
    emergencyContacts: 'Emergency Contacts',
    weight: 'Weight (kg)',
    height: 'Height (cm)',
    hospitalBag: 'Hospital Bag Checklist',
    mother: 'For Mother',
    baby: 'For Baby',
    documents: 'For Documents',
    yearlyCalendar: 'Yearly Calendar',
    audioPlayer: 'Womb & Nature Soundscapes',
    exerciseSplit: 'Interactive Exercises',
    vitalsTitle: 'Vitals Tracker',
    bpLabel: 'Blood Pressure',
    hbLabel: 'Hemoglobin',
    sugarLabel: 'Blood Sugar',
    saveBtn: 'Save Details',
    addContactBtn: 'Add Emergency Contact',
    relationLabel: 'Relationship (e.g., Husband)',
    phoneLabel: 'Phone Number',
    ruralTip: 'Welcome Mother! Feel safe and healthy.',
    scannedReportsList: 'Scanned Laboratory Reports',
    noReports: 'No reports scanned yet',
    normalStatus: 'Normal',
    borderlineStatus: 'Borderline',
    highRiskStatus: 'High Risk',
  
    // Auto-filled missing keys
    activeReminders: 'Active Reminders',
    addFirstReminder: 'Add your first reminder',
    alarm: 'Alarm',
    medicines: 'Medicines',
    noReminders: 'No reminders scheduled',
    reminderAlert: 'Reminder Alert',
    reminderPlaceholder: 'e.g., Take Folic Acid',
    reminderType: 'Reminder Type',
    remindersDesc: 'Never forget your medications or checkups',
    stopAlarm: 'Stop Alarm',
    suggestedQuestions: 'Suggested Questions',
    tapToMark: 'Tap to mark important dates',
    title: 'Title',
    typeMessage: 'Type your message...',
    voiceInput: 'Voice Input',
    
    // Custom Home page additions
    maternalVitalAnalytics: 'Maternal Vital Analytics',
    aiRiskAnalysis: 'AI Clinical Health Risk Analysis',
    aiRiskDesc: 'Automated screening checking clinical indicators & warning flags from vitals history.',
    combinedHealthScore: 'Combined Health Score',
    healthScoreDesc: 'This index estimates overall pregnancy condition based on current vitals. Regularly update reports to keep current.',
    biometricsNormal: 'All Biometrics in Target Range',
    biometricsNormalDesc: 'No abnormal BP, low hemoglobin, or elevated glucose levels detected. Keep maintaining regular nutrition and checkups.',
    activeWarnings: 'Active Warning Alerts',
    prescribedPrecautions: 'Prescribed Precautions',
    optimalHealth: 'Optimal Maternal Health',
    highClinicalRisk: 'High Clinical Risk',
    moderateClinicalRisk: 'Moderate Clinical Risk',
    stepMilestones: 'Step-by-Step Pregnancy Milestones Breakdown',
    stepMilestonesDesc: 'Explore baby size transitions, organ developments, and vital maternal advice Month by Month.',
    syncBluetoothCuff: 'Sync Bluetooth Wearable Cuff',
    oneTapSOS: 'ONE-TAP SOS EMERGENCY',
    targetRange: 'Target range',
    manualLog: '+ Manual Log',
    
    // Reminders
    remindersTitle: 'Maternal Reminders, Schedules & Alarms',
    remindersSub: 'Track daily medicine intake, vaccinations, and prenatal checkup meetings.',
    scheduleChecklists: 'Schedule Checklists',
    alarmActive: 'Alarm Active',
    noRemindersScheduled: 'No reminders scheduled. Use the form to add one.',
    vaccineTip: '💡 Tip: Vaccines like Tdap protect your baby from whooping cough. Complete them within weeks 28-36.',
    addNewReminder: 'Add New Reminder Checklist',
    reminderTitleLabel: 'Reminder Title / Medicine Name',
    customTitleLabel: 'Custom Title',
    dateLabel: 'Date',
    timeLabel: 'Time',
    reminderTypeLabel: 'Reminder Type',
    notesLabel: 'Notes / Instructions',
    activateAlarmLabel: 'Activate Alarm Notification Alert:',
    addToCalendarBtn: 'Add to Calendar',
    testAlarmBtn: 'Test Instant Alarm Notification',
    selectYearLabel: 'Select Year:',
    folicAcidOpt: 'Folic Acid',
    ironSupplementOpt: 'Iron Supplement',
    doctorAppointmentOpt: 'Doctor Appointment',
    tdapVaccinationOpt: 'Tdap Vaccination',
    customOpt: 'Custom...',
    timelineTitle: 'Clinical Maternal Immunization Timeline',
    fluVaccine: 'Flu Vaccine',
    fluVaccineDesc: 'Protects mother and baby from influenza during gestation and infancy.',
    tdapVaccine: 'Tdap Vaccine',
    tdapVaccineDesc: 'Protects baby from whooping cough (pertussis) during the first months of life.',
    rhogamVaccine: 'RhoGAM Vaccine',
    rhogamVaccineDesc: 'Prevents Rh sensitization in mothers with Rh-negative blood type.',
    completedOverdue: 'Completed / Overdue',
    dueThisWeek: 'Due This Week 🚨',
    dueInWeeksText: 'Due in {weeks} weeks ({days} days remaining)',
    testAlarmTriggered: '🔔 [TEST ALARM] Take Iron Supplement reminder triggered immediately!',

    // Care & SOS
    careMapTitle: 'Maternity Care, Pharmacies & Police safety Desks',
    careMapSub: 'Find nearby clinics, hospitals, 24/7 pharmacies, and police stations for safety backups.',
    autoGpsBtn: 'Auto GPS Geolocation',
    manualInputBtn: 'Manual Inputs / Address Search',
    setCoordsBtn: 'Set Coords',
    searchAddressPlaceholder: 'Search Address offline...',
    crisisTitle: 'Crisis Emergency Dispatch?',
    crisisSub: 'For immediate emergency medical team or safety security, invoke the One-Tap SOS alarm.',
    triggerSosBtn: 'TRIGGER EMERGENCY SOS ALARM NOW',
    awayText: 'away',
    connectedText: 'Connected',
    offlineTriageText: 'Offline Triage Active',

    // Profile
    pregnancyStartDateLabel: 'Pregnancy Start Date (Last Period Date)',
    preferredLanguageLabel: 'Preferred Language',
    weeksText: 'Weeks',
    contactsWarnedSub: 'Contacts warned automatically when SOS is clicked.',
    contactRemovedMsg: 'Contact removed from emergency registry',
    contactAddedMsg: 'New emergency contact registered successfully!',
    invalidPhoneMsg: 'Please enter a valid numeric phone number (digits only).',
    registerNewContactLabel: 'Register New Emergency Contact',
    contactNameLabel: 'Contact Name',
    contactRelationPlaceholder: 'Husband, Doctor, etc.',
    contactPhonePlaceholder: 'Phone Number',
    profileSavedMsg: 'Maternal health profile changes saved locally!',

    // Report Analysis
    easyOcrTitle: 'EasyOCR Report Verification',
    easyOcrSub: 'To unlock your personalized maternal diet guidelines and synchronize vitals, please select or drag your medical lab report (PDF/Image).',
    selectReportLabel: 'Select or drag your clinical report here',
    supportsReports: 'Supports Blood tests, Ultrasound, Glucose sheets',
    evaluationGallery: 'Judges Quick Evaluation Gallery',
    reportVerified: 'Medical Report Verified!',
    verifiedFile: 'Verified file:',
    scanAnother: 'Scan Another File',
    recommendedSuperfoods: 'Recommended Indian Superfoods',
    sampleDailyDiet: 'Sample Daily Diet Plan',
    avoidanceList: 'Dietary Avoidance list',
    localSyncStatus: 'Local & Sync Status',
    reportDeletedMsg: 'Report deleted successfully!',
    latitudeLabel: 'Latitude',
    longitudeLabel: 'Longitude',
    breakfastLabel: 'Breakfast',
    midDaySnackLabel: 'Mid-Day Snack',
    lunchLabel: 'Lunch',
    eveningSnackLabel: 'Evening Snack',
    dinnerLabel: 'Dinner',
    sample: 'Sample',
  },
  
  ta: {
    // Common
    appName: 'Mamora',
    tagline: 'AI இயக்கிய தாய்நல உதவியாளர்',
    welcome: 'வரவேற்கிறோம்',
    hello: 'வணக்கம்',
    goodbye: 'விடைபெறுகிறேன்',
    yes: 'ஆம்',
    no: 'இல்லை',
    cancel: 'ரத்து செய்',
    save: 'சேமி',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    add: 'சேர்',
    search: 'தேடு',
    loading: 'ஏற்றுகிறது...',
    error: 'பிழை',
    success: 'வெற்றி',
    title: 'தலைப்பு',
    
    // Auth
    login: 'உள்நுழை',
    signup: 'பதிவு செய்',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    phone: 'கைபேசி எண்',
    name: 'முழு பெயர்',
    dueDate: 'பிரசவ தேதி',
    pregnancyWeek: 'கர்ப்ப வாரம்',
    forgotPassword: 'கடவுச்சொல் மறந்ததா?',
    noAccount: 'கணக்கு இல்லையா?',
    haveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    fullName: 'முழு பெயர்',
    enterName: 'உங்கள் முழு பெயரை உள்ளிடவும்',
    age: 'வயது',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்து',
    createAccount: 'கணக்கை உருவாக்கு',
    
    // Navigation
    dashboard: 'டாஷ்போர்டு',
    nutrition: 'உணவு',
    reports: 'அறிக்கைகள்',
    records: 'பதிவுகள்',
    emergency: 'அவசரம்',
    reminders: 'நினைவூட்டல்கள்',
    hospitals: 'மருத்துவமனைகள்',
    pharmacy: 'மருந்தகம்',
    chatbot: 'AI உதவியாளர்',
    home: 'முகப்பு',
    roadmap: 'கருப்பயணக் காலக்கோடு',
    reportAnalysis: 'அறிக்கை ஆய்வு',
    map: 'பாதுகாப்பு & SOS',
    diet: 'உணவு',
    exercise: 'உடற்பயிற்சி',
    relax: 'ஓய்வு',
    sos: 'SOS',
    
    // Dashboard
    pregnancyJourney: 'கர்ப்ப பயணம்',
    week: 'வாரம்',
    trimester: 'மூன்றுமாத காலம்',
    babySize: 'குழந்தை அளவு',
    babyWeight: 'குழந்தை எடை',
    dailyTip: 'தினசரி குறிப்பு',
    nextAppointment: 'அடுத்த பரிசோதனை',
    
    // Nutrition
    aiNutrition: 'AI உணவு ஆலோசகர்',
    enterSymptoms: 'உங்கள் அறிகுறிகள் அல்லது உடல்நல நிலையை உள்ளிடவும்',
    getRecommendations: 'பரிந்துரைகளைப் பெறுங்கள்',
    recommendedFoods: 'பரிந்துரைக்கப்படும் உணவுகள்',
    avoidFoods: 'தவிர்க்க வேண்டிய உணவுகள்',
    dailyMealPlan: 'தினசரி உணவுத் திட்டம்',
    
    // Reports
    uploadReport: 'மருத்துவ அறிக்கையை பதிவேற்று',
    uploadImage: 'படம்/PDF பதிவேற்று',
    analyzing: 'ஆராய்கிறது...',
    hemoglobin: 'ஹீமோகுளோபின்',
    bloodPressure: 'இரத்த அழுத்தம்',
    bloodSugar: 'இரத்த சர்க்கரை',
    riskLevel: 'ஆபத்து நிலை',
    low: 'குறைவு',
    medium: 'நடுத்தரம்',
    high: 'அதிகம்',
    
    // Emergency
    emergencySOS: 'அவசரகால SOS',
    tapForHelp: 'உடனடி உதவிக்கு தட்டவும்',
    sendingAlert: 'எச்சரிக்கை அனுப்புகிறது...',
    alertSent: 'எச்சரிக்கை அனுப்பப்பட்டது!',
    nearbyHospitals: 'அருகிலுள்ள மருத்துவமனைகள்',
    
    // Chatbot
    smsSentTo: 'எஸ்எம்எஸ் அனுப்பப்பட்டது: ',
    locationShared: 'பகிரப்பட்ட இருப்பிடம்',
    emergencyServicesNotified: 'அவசர சேவைகளுக்கு தகவல் தெரிவிக்கப்பட்டது',
    alertLogged: 'எச்சரிக்கை பதிவு செய்யப்பட்ட நேரம்',
    protected: 'பாதுகாக்கப்பட்டது',
    youAreHere: 'நீங்கள் இங்கே இருக்கிறீர்கள்',
    placesFound: 'இடங்கள் கண்டறியப்பட்டன',
    hospital: 'மருத்துவமனை',
    police: 'காவல் நிலையம்',
    all: 'அனைத்தும்',
    confirmEmergency: 'அவசரநிலையை உறுதிப்படுத்துகிறீர்களா?',
    sosWarning: 'இது உங்கள் அவசரகால தொடர்புகளை எச்சரிப்பதுடன் உங்கள் இருப்பிடத்தையும் பகிரும்.',
    confirm: 'உறுதிப்படுத்து',
    helpOnWay: 'உதவி வந்து கொண்டிருக்கிறது',
    emergencyHub: 'அவசரகால மையம்',
    tapForEmergency: 'உடனடி உதவிக்கு தட்டவும்',
    ambulance: 'ஆம்புலன்ஸ்',
    
    // Relax/Meditation
    relaxTime: 'ஓய்வு நேரம்',
    forMothers: 'தாய்மார்களுக்கு',
    breathingExercise: 'மூச்சுப் பயிற்சி',
    ready: 'தயார்',
    start: 'தொடங்கு',
    stop: 'நிறுத்து',
    inhale: 'மூச்சை உள்ளிழுக்கவும்',
    hold: 'மூச்சை அடக்கவும்',
    exhale: 'மூச்சை வெளியேற்றவும்',
    inhaleFor4: '4 வினாடிகள் உள்ளிழுக்கவும்',
    holdFor7: '7 வினாடிகள் அடக்கவும்',
    exhaleFor8: '8 வினாடிகள் வெளியேற்றவும்',
    breathingDesc: '4-7-8 மூச்சு பயிற்சி கவலையைக் குறைத்து கர்ப்பத்தின் போது சிறந்த தூக்கத்தை வழங்குகிறது',
    moreSounds: 'மேலும் ஓய்வூட்டும் ஒலிகள்',
    benefitsForMothers: 'தாய்மார்களுக்கான நன்மைகள்',
    betterSleep: 'சிறந்த தூக்கம்',
    reducedStress: 'குறைந்த மன அழுத்தம்',
    calmMind: 'அமைதியான மனம்',
    babyBonding: 'குழந்தை உறவு',
    min: 'நிமி',
    
    // Exercises
    exerciseBook: 'உடற்பயிற்சி புத்தகம்',
    kcal: 'கலோரி',
    recommendedForYou: 'உங்களுக்கான பரிந்துரைகள்',
    startExercise: 'பயிற்சியை தொடங்கு',
    safetyTips: 'பாதுகாப்பு குறிப்புகள்',
    tip1: 'எந்த பயிற்சியையும் தொடங்குவதற்கு முன் மருத்துவரை அணுகவும்',
    tip2: 'நீரேற்றம் பேணவும் - முன், பின் மற்றும் போது தண்ணீர் குடிக்கவும்',
    tip3: 'மயக்கம் அல்லது அசௌகரியமாக உணர்ந்தால் உடனடியாக நிறுத்தவும்',
    tip4: '16 வாரத்திற்குப் பிறகு முதுகில் படுக்கும் பயிற்சிகளைத் தவிர்க்கவும்',
    previous: 'முந்தைய',
    next: 'அடுத்து',
    finish: 'முடி',
    easy: 'எளிது',
    hard: 'கடினம்',
    
    // Voice Assistant
    voiceAssistant: 'குரல் உதவியாளர்',
    tryAsking: 'கேட்க முயற்சிக்கவும்',
    navVoiceAssistant: '🎙️ குரல் உதவியாளர்',
    
    // Custom Additions for Mamora Overhaul - Tamil
    profile: 'சுயவிவரம்',
    emergencyContacts: 'அவசர தொடர்புகள்',
    weight: 'எடை (கிலோ)',
    height: 'உயரம் (செ.மீ)',
    hospitalBag: 'மருத்துவமனை பை சரிபார்ப்பு',
    mother: 'தாய்க்கு',
    baby: 'குழந்தைக்கு',
    documents: 'ஆவணங்களுக்கு',
    yearlyCalendar: 'வருடாந்திர நாட்காட்டி',
    audioPlayer: 'கருப்பை & இயற்கை ஒலிகள்',
    exerciseSplit: 'இடைவினை பயிற்சிகள்',
    vitalsTitle: 'உடல்நல அளவீடுகள்',
    bpLabel: 'இரத்த அழுத்தம்',
    hbLabel: 'ஹீமோகுளோபின்',
    sugarLabel: 'இரத்த சர்க்கரை',
    saveBtn: 'விவரங்களைச் சேமி',
    addContactBtn: 'அவசர தொடர்பைச் சேர்',
    relationLabel: 'உறவுமுறை (உம். கணவர்)',
    phoneLabel: 'கைபேசி எண்',
    ruralTip: 'தாய்மார்களை வரவேற்கிறோம்! பாதுகாப்பாகவும் ஆரோக்கியமாகவும் உணருங்கள்.',
    scannedReportsList: 'ஸ்கேன் செய்யப்பட்ட ஆய்வக அறிக்கைகள்',
    noReports: 'இன்னும் அறிக்கைகள் எதுவும் ஸ்கேன் செய்யப்படவில்லை',
    normalStatus: 'சாதாரண நிலை',
    borderlineStatus: 'எல்லைக்கோடு நிலை',
    highRiskStatus: 'அதி ஆபத்து',
  
    // Auto-filled missing keys
    addReminder: 'நினைவூட்டலைச் சேர்',
    bloodTests: 'இரத்தப் பரிசோதனைகள்',
    bpReadings: 'இரத்த அழுத்த அளவீடுகள்',
    completed: 'முடிந்தது',
    dailyGoal: 'தினசரி இலக்கு',
    dietProgress: 'உணவு முன்னேற்றம்',
    doctorVisit: 'மருத்துவர் சந்திப்பு',
    frequency: 'அதிர்வெண்',
    healthOverview: 'உடல்நல மேலோட்டம்',
    medicineReminder: 'மருந்து நினைவூட்டல்',
    quickActions: 'விரைவுச் செயல்கள்',
    supports: 'ஆதரிக்கிறது',
    tapToUpload: 'உங்கள் மருத்துவ அறிக்கையை பதிவேற்ற தட்டவும்',
    time: 'நேரம்',
    ultrasound: 'அல்ட்ராசவுண்ட்',
    viewAll: 'அனைத்தையும் காட்டு',
    viewPlan: 'திட்டத்தைப் பார்',
    activeReminders: 'செயலில் உள்ள நினைவூட்டல்கள்',
    addFirstReminder: 'உங்கள் முதல் நினைவூட்டலைச் சேர்க்கவும்',
    alarm: 'அலாரம்',
    medicines: 'மருந்துகள்',
    noReminders: 'நினைவூட்டல்கள் எதுவும் திட்டமிடப்படவில்லை',
    reminderAlert: 'நினைவூட்டல் எச்சரிக்கை',
    reminderPlaceholder: 'உம். போலிக் அமிலம் உட்கொள்ளவும்',
    reminderType: 'நினைவூட்டல் வகை',
    remindersDesc: 'உங்கள் மருந்துகள் அல்லது பரிசோதனைகளை மறக்காதீர்கள்',
    stopAlarm: 'அலாரத்தை நிறுத்து',
    suggestedQuestions: 'பரிந்துரைக்கப்பட்ட கேள்விகள்',
    tapToMark: 'முக்கிய தேதிகளைக் குறிக்க தட்டவும்',
    typeMessage: 'உங்கள் செய்தியை தட்டச்சு செய்யவும்...',
    voiceInput: 'குரல் உள்ளீடு',
    
    // Custom Home page additions - Tamil
    maternalVitalAnalytics: 'தாய்வழி முக்கிய உடலளவீடுகள்',
    aiRiskAnalysis: 'AI மருத்துவ உடல்நல அபாய ஆய்வு',
    aiRiskDesc: 'உடல்நல அளவீடுகளின் வரலாற்றைக் கொண்டு தானியங்கி முறையில் கண்டறியப்படும் அபாய எச்சரிக்கைகள்.',
    combinedHealthScore: 'ஒட்டுமொத்த ஆரோக்கிய மதிப்பெண்',
    healthScoreDesc: 'இந்த அளவீடு தற்போதைய உடல்நல நிலவரங்களைக் கொண்டு ஒட்டுமொத்த கர்ப்ப நிலையை மதிப்பிடுகிறது. விவரங்களைப் புதுப்பிக்கவும்.',
    biometricsNormal: 'அனைத்து அளவீடுகளும் சரியான வரம்பில் உள்ளன',
    biometricsNormalDesc: 'அசாதாரண இரத்த அழுத்தம், குறைந்த ஹீமோகுளோபின் அல்லது அதிக சர்க்கரை கண்டறியப்படவில்லை. ஆரோக்கியமான உணவு முறையைத் தொடரவும்.',
    activeWarnings: 'செயலில் உள்ள எச்சரிக்கைகள்',
    prescribedPrecautions: 'பரிந்துரைக்கப்படும் முன்னெச்சரிக்கைகள்',
    optimalHealth: 'உகந்த தாய்வழி ஆரோக்கியம்',
    highClinicalRisk: 'அதி உயர் மருத்துவ ஆபத்து',
    moderateClinicalRisk: 'நடுத்தர மருத்துவ ஆபத்து',
    stepMilestones: 'வாராந்திர/மாதாந்திர கர்ப்ப கால மைல்கற்கள் விவரம்',
    stepMilestonesDesc: 'மாதந்தோறும் குழந்தையின் வளர்ச்சி நிலை, உறுப்புகள் உருவாக்கம் மற்றும் தாய்க்கான ஆலோசனைகளை ஆராயுங்கள்.',
    syncBluetoothCuff: 'புளூடூத் கருவியை ஒத்திசைக்கவும்',
    oneTapSOS: 'ஒரு தட்டல் அவசர SOS',
    targetRange: 'சரியான அளவு வரம்பு',
    manualLog: '+ கைமுறைப் பதிவு',
    
    // Reminders - Tamil
    remindersTitle: 'தாய்வழி நினைவூட்டல்கள், அட்டவணைகள் & அலாரங்கள்',
    remindersSub: 'தினசரி மருந்து உட்கொள்ளல், தடுப்பூசிகள் மற்றும் பிறப்புக்கு முந்தைய பரிசோதனை சந்திப்புகளைக் கண்காணிக்கவும்.',
    scheduleChecklists: 'அட்டவணை சரிபார்ப்புப் பட்டியல்',
    alarmActive: 'அலாரம் செயல்பாட்டில் உள்ளது',
    noRemindersScheduled: 'நினைவூட்டல்கள் எதுவும் திட்டமிடப்படவில்லை. ஒன்றைச் சேர்க்க படிவத்தைப் பயன்படுத்தவும்.',
    vaccineTip: '💡 குறிப்பு: டிடாப் (Tdap) போன்ற தடுப்பூசிகள் உங்கள் குழந்தையை கக்குவான் இருமலில் இருந்து பாதுகாக்கின்றன. இவற்றை 28-36 வாரங்களுக்குள் முடித்துக்கொள்ளுங்கள்.',
    addNewReminder: 'புதிய நினைவூட்டல் சரிபார்ப்புப் பட்டியலைச் சேர்',
    reminderTitleLabel: 'நினைவூட்டல் தலைப்பு / மருந்தின் பெயர்',
    customTitleLabel: 'தனிப்பயன் தலைப்பு',
    dateLabel: 'தேதி',
    timeLabel: 'நேரம்',
    reminderTypeLabel: 'நினைவூட்டல் வகை',
    notesLabel: 'குறிப்புகள் / வழிமுறைகள்',
    activateAlarmLabel: 'அலாரம் அறிவிப்பு எச்சரிக்கையைச் செயல்படுத்து:',
    addToCalendarBtn: 'நாட்காட்டியில் சேர்',
    testAlarmBtn: 'உடனடி அலாரம் அறிவிப்பைச் சோதிக்கவும்',
    selectYearLabel: 'ஆண்டைத் தேர்ந்தெடுக்கவும்:',
    folicAcidOpt: 'போலிக் அமிலம்',
    ironSupplementOpt: 'இரும்புச் சத்து துணை',
    doctorAppointmentOpt: 'மருத்துவர் சந்திப்பு',
    tdapVaccinationOpt: 'டிடாப் தடுப்பூசி',
    customOpt: 'தனிப்பயன்...',
    timelineTitle: 'மருத்துவ தாய்வழி தடுப்பூசி காலக்கோடு',
    fluVaccine: 'காய்ச்ல் தடுப்பூசி (Flu Vaccine)',
    fluVaccineDesc: 'கர்ப்ப காலத்திலும் மற்றும் குழந்தை பருவத்திலும் தாயையும் சேயையும் இன்ஃப்ளூயன்ஸா காய்ச்சலிலிருந்து பாதுகாக்கிறது.',
    tdapVaccine: 'டிடாப் தடுப்பூசி (Tdap Vaccine)',
    tdapVaccineDesc: 'குழந்தையின் முதல் சில மாதங்களில் கக்குவான் இருமலில் இருந்து குழந்தையைப் பாதுகாக்கிறது.',
    rhogamVaccine: 'ரோகாம் தடுப்பூசி (RhoGAM Vaccine)',
    rhogamVaccineDesc: 'Rh-நெகட்டிவ் இரத்த வகை கொண்ட தாய்மார்களுக்கு Rh உணர்திறனைத் தடுக்கிறது.',
    completedOverdue: 'முடிக்கப்பட்டது / காலாவதியானது',
    dueThisWeek: 'இந்த வாரம் செலுத்தப்பட வேண்டும் 🚨',
    dueInWeeksText: '{weeks} வாரங்களில் செலுத்தப்பட வேண்டும் ({days} நாட்கள் மீதமுள்ளன)',
    testAlarmTriggered: '🔔 [சோதனை அலாரம்] இரும்புச் சத்து நினைவூட்டல் உடனடியாக இயக்கப்பட்டது!',

    // Care & SOS - Tamil
    careMapTitle: 'தாய்மைப் பராமரிப்பு, மருந்தகங்கள் & காவல் உதவி மையங்கள்',
    careMapSub: 'பாதுகாப்பு வசதிகளுக்காக அருகிலுள்ள கிளினிக்குகள், மருத்துவமனைகள், 24/7 மருந்தகங்கள் மற்றும் காவல் நிலையங்களைக் கண்டறியவும்.',
    autoGpsBtn: 'தானியங்கி ஜிபிஎஸ் இருப்பிடம்',
    manualInputBtn: 'கைமுறை உள்ளீடு / முகவரி தேடல்',
    setCoordsBtn: 'அமைப்புகள்',
    searchAddressPlaceholder: 'முகவரியை ஆஃப்லைனில் தேடுங்கள்...',
    crisisTitle: 'அவசரகால உதவி தேவையா?',
    crisisSub: 'உடனடி அவசர மருத்துவக் குழு அல்லது பாதுகாப்புச் சேவைக்கு, ஒரு தட்டல் SOS அலாரத்தை இயக்கவும்.',
    triggerSosBtn: 'உடனடியாக அவசர SOS அலாரத்தை இயக்கவும்',
    awayText: 'தொலைவில்',
    connectedText: 'இணைக்கப்பட்டுள்ளது',
    offlineTriageText: 'ஆஃப்லைன் அறிகுறி பகுப்பாய்வு செயல்படுகிறது',

    // Profile - Tamil
    pregnancyStartDateLabel: 'கர்ப்பம் தொடங்கிய தேதி (கடைசி மாதவிடாய் தேதி)',
    preferredLanguageLabel: 'விருப்பமான மொழி',
    weeksText: 'வாரங்கள்',
    contactsWarnedSub: 'SOS கிளிக் செய்யப்படும்போது தொடர்புகளுக்கு தானாகவே எச்சரிக்கை விடுக்கப்படும்.',
    contactRemovedMsg: 'அவசரகால பதிவேட்டில் இருந்து தொடர்பு நீக்கப்பட்டது',
    contactAddedMsg: 'புதிய அவசர தொடர்பு வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
    invalidPhoneMsg: 'தயவுசெய்து சரியான எண்களைக் கொண்ட தொலைபேசி எண்ணை உள்ளிடவும் (எண்கள் மட்டுமே).',
    registerNewContactLabel: 'புதிய அவசர தொடர்பை பதிவு செய்',
    contactNameLabel: 'தொடர்பு பெயர்',
    contactRelationPlaceholder: 'கணவர், மருத்துவர், முதலியன',
    contactPhonePlaceholder: 'தொலைபேசி எண்',
    profileSavedMsg: 'தாய்வழி சுகாதார சுயவிவர மாற்றங்கள் சேமிக்கப்பட்டன!',

    // Report Analysis - Tamil
    easyOcrTitle: 'ஈஸி ஓசிஆர் அறிக்கை சரிபார்ப்பு',
    easyOcrSub: 'உங்கள் தனிப்பயனாக்கப்பட்ட தாய்வழி உணவு வழிகாட்டுதல்களைத் திறக்கவும் மற்றும் உடல்நல அளவீடுகளை ஒத்திசைக்கவும், தயவுசெய்து உங்கள் மருத்துவ ஆய்வக அறிக்கையை (PDF/படம்) தேர்ந்தெடுக்கவும் அல்லது இழுக்கவும்.',
    selectReportLabel: 'உங்கள் மருத்துவ அறிக்கையை இங்கே தேர்ந்தெடுக்கவும் அல்லது இழுக்கவும்',
    supportsReports: 'இரத்தப் பரிசோதனைகள், அல்ட்ராசவுண்ட், குளுக்கோஸ் தாள்களை ஆதரிக்கிறது',
    evaluationGallery: 'நடுவர்களின் விரைவான மதிப்பீட்டு தொகுப்பு',
    reportVerified: 'மருத்துவ அறிக்கை சரிபார்க்கப்பட்டது!',
    verifiedFile: 'சரிபார்க்கப்பட்ட கோப்பு:',
    scanAnother: 'மற்றொரு கோப்பை ஸ்கேன் செய்',
    recommendedSuperfoods: 'பரிந்துரைக்கப்படும் இந்திய சூப்பர்ஃபுட்ஸ்',
    sampleDailyDiet: 'மாதிரி தினசரி உணவுத் திட்டம்',
    avoidanceList: 'தவிர்க்க வேண்டிய உணவுகளின் பட்டியல்',
    localSyncStatus: 'உள்ளூர் & ஒத்திசைவு நிலை',
    reportDeletedMsg: 'அறிக்கை வெற்றிகரமாக நீக்கப்பட்டது!',
    latitudeLabel: 'அட்சரேகை',
    longitudeLabel: 'தீர்க்கரேகை',
    breakfastLabel: 'காலை உணவு',
    midDaySnackLabel: 'மதிய சிற்றுண்டி',
    lunchLabel: 'மதிய உணவு',
    eveningSnackLabel: 'மாலை சிற்றுண்டி',
    dinnerLabel: 'இரவு உணவு',
    sample: 'மாதிரி',
  },
  
  hi: {
    // Common
    appName: 'Mamora',
    tagline: 'AI-संचालित मातृ स्वास्थ्य साथी',
    welcome: 'स्वागत है',
    hello: 'नमस्ते',
    goodbye: 'अलविदा',
    yes: 'हाँ',
    no: 'नहीं',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    add: 'जोड़ें',
    search: 'खोजें',
    loading: 'लोड हो रहा है...',
    error: 'त्रुटि',
    success: 'सफलता',
    title: 'शीर्षक',
    
    // Auth
    login: 'लॉग इन',
    signup: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    phone: 'फोन नंबर',
    name: 'पूरा नाम',
    dueDate: 'प्रसव की तारीख',
    pregnancyWeek: 'गर्भावस्था सप्ताह',
    forgotPassword: 'पासवर्ड भूल गए?',
    noAccount: 'खाता नहीं है?',
    haveAccount: 'पहले से खाता है?',
    fullName: 'पूरा नाम',
    enterName: 'अपना पूरा नाम दर्ज करें',
    age: 'उम्र',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    createAccount: 'खाता बनाएं',
    
    // Navigation
    dashboard: 'डैशबोर्ड',
    nutrition: 'पोषण',
    reports: 'रिपोर्ट्स',
    records: 'रिकॉर्ड्स',
    emergency: 'आपातकालीन',
    reminders: 'रिमाइंडर',
    hospitals: 'अस्पताल',
    pharmacy: 'फार्मेसी',
    chatbot: 'AI सहायक',
    home: 'होम',
    roadmap: 'समयरेखा',
    reportAnalysis: 'रिपोर्ट विश्लेषण',
    map: 'सुरक्षा और SOS',
    diet: 'आहार',
    exercise: 'व्यायाम',
    relax: 'आराम',
    sos: 'एसओएस',
    
    // Dashboard
    pregnancyJourney: 'गर्भावस्था यात्रा',
    week: 'सप्ताह',
    trimester: 'त्रैमासिक',
    babySize: 'बच्चे का आकार',
    babyWeight: 'बच्चे का वजन',
    dailyTip: 'दैनिक सुझाव',
    nextAppointment: 'अगली नियुक्ति',
    uploadReport: 'रिपोर्ट अपलोड करें',
    viewAll: 'सभी देखें',
    tapToUpload: 'अपनी मेडिकल रिपोर्ट अपलोड करने के लिए टैप करें',
    supports: 'समर्थन करता है',
    bloodTests: 'रक्त परीक्षण',
    ultrasound: 'अल्ट्रासाउंड',
    bpReadings: 'बीपी रीडिंग',
    healthOverview: 'स्वास्थ्य अवलोकन',
    dietProgress: 'आहार प्रगति',
    viewPlan: 'योजना देखें',
    quickActions: 'त्वरित कार्रवाई',
    completed: 'पूरा हुआ',
    dailyGoal: 'दैनिक लक्ष्य',
    
    // Nutrition
    aiNutrition: 'AI पोषण सलाहकार',
    enterSymptoms: 'अपने लक्षण दर्ज करें',
    getRecommendations: 'सुझाव प्राप्त करें',
    recommendedFoods: 'अनुशंसित खाद्य पदार्थ',
    avoidFoods: 'बचने योग्य खाद्य पदार्थ',
    dailyMealPlan: 'दैनिक भोजन योजना',
    
    // Reports
    uploadImage: 'छवि/PDF अपलोड करें',
    analyzing: 'विश्लेषण कर रहा है...',
    hemoglobin: 'हीमोग्लोबिन',
    bloodPressure: 'रक्तचाप',
    bloodSugar: 'रक्त शर्करा',
    riskLevel: 'जोखिम स्तर',
    low: 'कम',
    medium: 'मध्यम',
    high: 'उच्च',
    
    // Emergency - Hindi
    emergencySOS: 'आपातकालीन SOS',
    tapForHelp: 'तत्काल सहायता के लिए टैप करें',
    sendingAlert: 'अलर्ट भेज रहा है...',
    alertSent: 'अलर्ट भेजा गया!',
    nearbyHospitals: 'पास के अस्पताल',
    
    // Reminders - Hindi
    medicineReminder: 'दवा रिमाइंडर',
    doctorVisit: 'डॉक्टर का दौरा',
    addReminder: 'रिमाइंडर जोड़ें',
    time: 'समय',
    frequency: 'आवृत्ति',
    alarm: 'अलार्म',
    stopAlarm: 'अलार्म बंद करें',
    reminderAlert: 'रिमाइंडर',
    remindersDesc: 'अपनी दवाएं या अनुबंध कभी न भूलें',
    noReminders: 'कोई रिमाइंडर नहीं',
    addFirstReminder: 'अपना पहला रिमाइंडर जोड़ें',
    activeReminders: 'सक्रिय',
    medicines: 'दवाइयां',
    tapToMark: 'महत्वपूर्ण तिथियां चिह्नित करने के लिए टैप करें',
    reminderType: 'प्रकार',
    reminderPlaceholder: 'जैसे, फोलिक एसिड लें',
    
    // Chatbot - Hindi
    typeMessage: 'अपना संदेश लिखें...',
    voiceInput: 'वॉइस इनपुट',
    suggestedQuestions: 'सुझाए गए प्रश्न',
    
    // Emergency Alert Details - Hindi
    smsSentTo: 'SMS भेजा गया',
    locationShared: 'स्थान साझा किया गया',
    emergencyServicesNotified: 'आपातकालीन सेवाओं को सूचित किया गया',
    alertLogged: 'अलर्ट का समय',
    protected: 'सुरक्षित',
    youAreHere: 'आप यहाँ हैं',
    placesFound: 'स्थान मिले',
    hospital: 'अस्पताल',
    police: 'पुलिस',
    all: 'सभी',
    // duplicate removed: hospitals: 'अस्पताल',
    confirmEmergency: 'आपातकाल की पुष्टि करें?',
    sosWarning: 'यह आपके आपातकालीन संपर्कों को सचेत करेगा और आपका स्थान साझा करेगा।',
    confirm: 'पुष्टि करें',
    // duplicate removed: alertSent: 'अलर्ट भेजा गया!',
    helpOnWay: 'मदद आ रही है',
    emergencyHub: 'आपातकालीन केंद्र',
    tapForEmergency: 'तत्काल सहायता के लिए टैप करें',
    ambulance: 'एम्बुलेंस',
    
    // Relax/Meditation - Hindi
    relaxTime: 'आराम का समय',
    forMothers: 'माताओं के लिए',
    breathingExercise: 'सांस व्यायाम',
    ready: 'तैयार',
    start: 'शुरू करें',
    stop: 'रोकें',
    inhale: 'सांस लें',
    hold: 'रोकें',
    exhale: 'सांस छोड़ें',
    inhaleFor4: '4 सेकंड के लिए सांस लें',
    holdFor7: '7 सेकंड के लिए रोकें',
    exhaleFor8: '8 सेकंड के लिए सांस छोड़ें',
    breathingDesc: '4-7-8 सांस व्यायाम चिंता को कम करता है और गर्भावस्था के दौरान बेहतर नींद देता है',
    moreSounds: 'और आरामदायक ध्वनियाँ',
    benefitsForMothers: 'माताओं के लिए लाभ',
    betterSleep: 'बेहतर नींद',
    reducedStress: 'कम तनाव',
    calmMind: 'शांत मन',
    babyBonding: 'बच्चे के साथ बंधन',
    min: 'मिनट',
    
    // Exercises - Hindi
    exerciseBook: 'व्यायाम पुस्तक',
    // duplicate removed: trimester: 'त्रैमासिक',
    // duplicate removed: completed: 'पूरा हुआ',
    // duplicate removed: dailyGoal: 'दैनिक लक्ष्य',
    // duplicate removed: min: 'मिनट',
    kcal: 'कैलोरी',
    recommendedForYou: 'आपके लिए अनुशंसित',
    startExercise: 'व्यायाम शुरू करें',
    safetyTips: 'सुरक्षा सुझाव',
    tip1: 'कोई भी व्यायाम शुरू करने से पहले अपने डॉक्टर से परामर्श करें',
    tip2: 'हाइड्रेटेड रहें - पहले, दौरान और बाद में पानी पिएं',
    tip3: 'अगर चक्कर आए या असुविधा महसूस हो तो तुरंत रोकें',
    tip4: '16 सप्ताह के बाद पीठ के बल लेटने वाले व्यायामों से बचें',
    previous: 'पिछला',
    next: 'अगला',
    finish: 'समाप्त',
    easy: 'आसान',
    // duplicate removed: medium: 'मध्यम',
    hard: 'कठिन',
    
    // Voice Assistant - Hindi
    voiceAssistant: 'वॉयस सहायक',
    tryAsking: 'पूछने का प्रयास करें',
    navVoiceAssistant: '🎙️ वॉयस सहायक',
    
    // Custom Additions for Mamora Overhaul - Hindi
    profile: 'प्रोफ़ाइल',
    emergencyContacts: 'आपातकालीन संपर्क',
    weight: 'वजन (किग्रा)',
    height: 'लंबाई (सेमी)',
    hospitalBag: 'अस्पताल बैग चेकलिस्ट',
    mother: 'मां के लिए',
    baby: 'बच्चे के लिए',
    documents: 'दस्तावेजों के लिए',
    yearlyCalendar: 'वार्षिक कैलेंडर',
    audioPlayer: 'गर्भ और प्रकृति ध्वनियां',
    exerciseSplit: 'इंटरएक्टिव व्यायाम',
    vitalsTitle: 'स्वास्थ्य विटल्स',
    bpLabel: 'रक्तचाप',
    hbLabel: 'हीमोग्लोबिन',
    sugarLabel: 'ब्लड शुगर',
    saveBtn: 'विवरण सहेजें',
    addContactBtn: 'आपातकालीन संपर्क जोड़ें',
    relationLabel: 'संबंध (जैसे, पति)',
    phoneLabel: 'फोन नंबर',
    ruralTip: 'माताओं का स्वागत है! सुरक्षित और स्वस्थ महसूस करें।',
    scannedReportsList: 'स्कैन की गई लैब रिपोर्ट',
    noReports: 'अभी तक कोई रिपोर्ट स्कैन नहीं की गई है',
    normalStatus: 'सामान्य',
    borderlineStatus: 'सीमा रेखा',
    highRiskStatus: 'उच्च जोखिम',
    
    // Custom Home page additions - Hindi
    maternalVitalAnalytics: 'मातृ महत्वपूर्ण स्वास्थ्य विश्लेषण',
    aiRiskAnalysis: 'AI नैदानिक स्वास्थ्य जोखिम विश्लेषण',
    aiRiskDesc: 'महत्वपूर्ण स्वास्थ्य संकेतकों और चेतावनी झंडे की स्वचालित स्क्रीनिंग जांच।',
    combinedHealthScore: 'संयुक्त स्वास्थ्य स्कोर',
    healthScoreDesc: 'यह सूचकांक वर्तमान स्वास्थ्य संकेतकों के आधार पर गर्भावस्था की स्थिति का अनुमान लगाता है।',
    biometricsNormal: 'सभी बायोमेट्रिक्स सामान्य सीमा में हैं',
    biometricsNormalDesc: 'कोई असामान्य बीपी, कम हीमोग्लोबिन या बढ़ा हुआ ग्लूकोज नहीं मिला है। नियमित पोषण बनाए रखें।',
    activeWarnings: 'सक्रिय चेतावनी अलर्ट',
    prescribedPrecautions: 'निर्धारित सावधानियां',
    optimalHealth: 'सर्वोत्तम मातृ स्वास्थ्य',
    highClinicalRisk: 'उच्च नैदानिक जोखिम',
    moderateClinicalRisk: 'मध्यम नैदानिक जोखिम',
    stepMilestones: 'कदम-दर-कदम गर्भावस्था मील के पत्थर का विवरण',
    stepMilestonesDesc: 'महीने दर महीने बच्चे के विकास, अंगों और मातृ स्वास्थ्य सलाह के बारे में जानें।',
    syncBluetoothCuff: 'ब्लूटूथ कफ सिंक करें',
    oneTapSOS: 'वन-टैप एसओएस आपातकालीन',
    targetRange: 'लक्ष्य सीमा',
    manualLog: '+ मैनुअल लॉग',
    
    // Reminders - Hindi
    remindersTitle: 'मातृ अनुस्मारक, कार्यक्रम और अलार्म',
    remindersSub: 'दैनिक दवा सेवन, टीकाकरण और प्रसवपूर्व जांच बैठकों को ट्रैक करें।',
    scheduleChecklists: 'अनुसूची चेकलिस्ट',
    alarmActive: 'अलार्म सक्रिय है',
    noRemindersScheduled: 'कोई रिमाइंडर शेड्यूल नहीं है। जोड़ने के लिए फॉर्म का उपयोग करें।',
    vaccineTip: '💡 टिप: Tdap जैसे टीके आपके बच्चे को काली खांसी से बचाते हैं। उन्हें सप्ताह 28-36 के भीतर पूरा करें।',
    addNewReminder: 'नया अनुस्मारक चेकलिस्ट जोड़ें',
    reminderTitleLabel: 'अनुस्मारक शीर्षक / दवा का नाम',
    customTitleLabel: 'कस्टम शीर्षक',
    dateLabel: 'तारीख',
    timeLabel: 'समय',
    reminderTypeLabel: 'अनुस्मारक प्रकार',
    notesLabel: 'नोट्स / निर्देश',
    activateAlarmLabel: 'अलार्म अधिसूचना चेतावनी सक्रिय करें:',
    addToCalendarBtn: 'कैलेंडर में जोड़ें',
    testAlarmBtn: 'त्वरित अलार्म अधिसूचना का परीक्षण करें',
    selectYearLabel: 'वर्ष चुनें:',
    folicAcidOpt: 'फॉलिक एसिड',
    ironSupplementOpt: 'आयरन सप्लीमेंट',
    doctorAppointmentOpt: 'डॉक्टर अपॉइंटमेंट',
    tdapVaccinationOpt: 'Tdap टीकाकरण',
    customOpt: 'कस्टम...',
    timelineTitle: 'नैदानिक मातृ टीकाकरण समयरेखा',
    fluVaccine: 'फ्लू का टीका (Flu Vaccine)',
    fluVaccineDesc: 'गर्भावस्था और शिशु अवस्था के दौरान मां और बच्चे को इन्फ्लूएंजा से बचाता है।',
    tdapVaccine: 'Tdap का टीका (Tdap Vaccine)',
    tdapVaccineDesc: 'जीवन के पहले महीनों के दौरान बच्चे को काली खांसी (पेटुसिस) से बचाता है।',
    rhogamVaccine: 'RhoGAM का टीका (RhoGAM Vaccine)',
    rhogamVaccineDesc: 'आरएच-नेगेटिव रक्त प्रकार वाली माताओं में आरएच संवेदीकरण को रोकता है।',
    completedOverdue: 'पूर्ण / अतिदेय',
    dueThisWeek: 'इस सप्ताह देय 🚨',
    dueInWeeksText: '{weeks} सप्ताह में देय ({days} दिन शेष)',
    testAlarmTriggered: '🔔 [परीक्षण अलार्म] आयरन सप्लीमेंट अनुस्मारक तुरंत चालू हो गया!',

    // Care & SOS - Hindi
    careMapTitle: 'मातृत्व देखभाल, फार्मेसी और पुलिस सुरक्षा डेस्क',
    careMapSub: 'सुरक्षा बैकअप के लिए नजदीकी क्लीनिक, अस्पताल, 24/7 फार्मेसी और पुलिस स्टेशन खोजें।',
    autoGpsBtn: 'ऑटो जीपीएस जियोलोकेशन',
    manualInputBtn: 'मैनुअल इनपुट / पता खोज',
    setCoordsBtn: 'निर्देशांक सेट करें',
    searchAddressPlaceholder: 'ऑफ़लाइन पता खोजें...',
    crisisTitle: 'आपातकालीन संकट प्रेषण?',
    crisisSub: 'तत्काल आपातकालीन चिकित्सा टीम या सुरक्षा के लिए, वन-टैप एसओएस अलार्म सक्रिय करें।',
    triggerSosBtn: 'अभी आपातकालीन एसओएस अलार्म सक्रिय करें',
    awayText: 'दूर',
    connectedText: 'जुड़ा हुआ है',
    offlineTriageText: 'ऑफ़लाइन ट्राइएज सक्रिय',

    // Profile - Hindi
    pregnancyStartDateLabel: 'गर्भावस्था शुरू होने की तारीख (अंतिम मासिक धर्म की तारीख)',
    preferredLanguageLabel: 'पसंदीदा भाषा',
    weeksText: 'सप्ताह',
    contactsWarnedSub: 'एसओएस पर क्लिक करने पर संपर्कों को स्वचालित रूप से चेतावनी दी जाएगी।',
    contactRemovedMsg: 'आपातकालीन रजिस्ट्री से संपर्क हटा दिया गया',
    contactAddedMsg: 'नया आपातकालीन संपर्क सफलतापूर्वक पंजीकृत हो गया!',
    invalidPhoneMsg: 'कृपया एक वैध संख्यात्मक फ़ोन नंबर दर्ज करें (केवल अंक)।',
    registerNewContactLabel: 'नया आपातकालीन संपर्क पंजीकृत करें',
    contactNameLabel: 'संपर्क का नाम',
    contactRelationPlaceholder: 'पति, डॉक्टर, आदि',
    contactPhonePlaceholder: 'फ़ोन नंबर',
    profileSavedMsg: 'मातृ स्वास्थ्य प्रोफ़ाइल परिवर्तन स्थानीय रूप से सहेजे गए!',

    // Report Analysis - Hindi
    easyOcrTitle: 'ईजी ओसीआर रिपोर्ट सत्यापन',
    easyOcrSub: 'अपने व्यक्तिगत मातृ आहार दिशानिर्देशों को अनलॉक करने और महत्वपूर्ण स्वास्थ्य संकेतकों को सिंक करने के लिए, कृपया अपनी मेडिकल लैब रिपोर्ट (PDF/छवि) चुनें या खींचें।',
    selectReportLabel: 'अपनी क्लिनिकल रिपोर्ट यहाँ चुनें या खींचें',
    supportsReports: 'रक्त परीक्षण, अल्ट्रासाउंड, ग्लूकोज शीट का समर्थन करता है',
    evaluationGallery: 'जजों की त्वरित मूल्यांकन गैलरी',
    reportVerified: 'मेडिकल रिपोर्ट सत्यापित हो गई!',
    verifiedFile: 'सत्यापित फ़ाइल:',
    scanAnother: 'अन्य फ़ाइल स्कैन करें',
    recommendedSuperfoods: 'अनुशंसित भारतीय सुपरफूड्स',
    sampleDailyDiet: 'दैनिक आहार योजना का नमूना',
    avoidanceList: 'परहेज करने योग्य खाद्य पदार्थों की सूची',
    localSyncStatus: 'स्थानीय और सिंक स्थिति',
    reportDeletedMsg: 'रिपोर्ट सफलतापूर्वक हटा दी गई!',
    latitudeLabel: 'अक्षांश',
    longitudeLabel: 'देशांतर',
    breakfastLabel: 'नाश्ता',
    midDaySnackLabel: 'दोपहर का नाश्ता',
    lunchLabel: 'दोपहर का भोजन',
    eveningSnackLabel: 'शाम का नाश्ता',
    dinnerLabel: 'रात का भोजन',
    sample: 'नमूना',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('maatrucare_language');
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('maatrucare_language', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
    languages: [
      { code: 'en', name: 'English', flag: '🇮🇳' },
      { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
      { code: 'hi', name: 'हिंदी', flag: '🇮🇳' }
    ]
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}

export default LanguageContext;
